In [49]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

In [50]:
dataset = np.array([['kor',70], ['math', 80]])
df = pd.DataFrame(dataset, columns=['class','score'])

In [51]:
filepath = "./dataset/data.csv"
data = pd.read_csv(filepath, na_values='NA', encoding='utf-8')

In [52]:
data.to_csv('./dataset/result.csv', header=True,index=True, encoding='utf-8')

In [53]:
df.to_csv('./dataset/result2.csv', header=True,index=True, encoding='utf-8')

In [54]:
df.index

RangeIndex(start=0, stop=2, step=1)

In [55]:
list(df.index)

[0, 1]

In [56]:
df.index = ['a', 'b']
df.index

Index(['a', 'b'], dtype='str')

In [57]:
df

  class score
a   kor    70
b  math    80

In [58]:
df.index

Index(['a', 'b'], dtype='str')

In [59]:
df.set_index('class', append=False, drop=True, inplace=True)

In [60]:
df

      score
class
kor      70
math     80

In [61]:
df.reset_index(drop=False, inplace=True)

In [62]:
df

  class score
0   kor    70
1  math    80

In [63]:
iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
print(iris_df)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [64]:
print(type(iris))
print(type(iris.data))
print(type(iris_df))
print(type(iris.feature_names))

<class 'sklearn.utils._bunch.Bunch'>
<class 'numpy.ndarray'>
<class 'pandas.DataFrame'>
<class 'list'>

In [65]:
iris_df.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [66]:
iris_df.tail()

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

In [67]:
iris_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB

In [68]:
iris_df.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000

In [69]:
print(type(iris_df.index))
print(iris_df.index)

<class 'pandas.RangeIndex'>
RangeIndex(start=0, stop=150, step=1)

In [70]:
print(type(iris_df.columns))
print(iris_df.columns)

<class 'pandas.Index'>
Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='str')

In [71]:
iris_df.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']

In [72]:
print(type(iris_df.columns))
print(iris_df.columns)

<class 'pandas.Index'>
Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], dtype='str')

In [73]:
iris_df.columns = iris_df.columns.str.replace('_', '-')

In [74]:
iris_df.columns

Index(['sepal-length', 'sepal-width', 'petal-length', 'petal-width'], dtype='str')

In [75]:
print(type(iris_df.columns))
print(type(iris_df.columns.str))
print(type(iris_df.columns.str.replace('_', '-')))
print(iris_df.columns.str)

<class 'pandas.Index'>
<class 'pandas.core.strings.accessor.StringMethods'>
<class 'pandas.Index'>
<pandas.core.strings.accessor.StringMethods object at 0x000001A041779350>

In [76]:
print(iris_df.dtypes)
print(type(iris_df.dtypes))

sepal-length    float64
sepal-width     float64
petal-length    float64
petal-width     float64
dtype: object
<class 'pandas.Series'>

In [77]:
iris_df["sepal-length"] = iris_df["sepal-length"].astype('int')
iris_df[["sepal-width", "petal-length"]] = iris_df[["sepal-width", "petal-length"]].astype('int')
iris_df.head(3)

   sepal-length  sepal-width  petal-length  petal-width
0             5            3             1          0.2
1             4            3             1          0.2
2             4            3             1          0.2

In [78]:
print(type(iris_df["sepal-length"]))
print(type(iris_df["sepal-length"].astype('int')))
print(type(iris_df[["sepal-width", "petal-length"]]))
print(type(iris_df[["sepal-width", "petal-length"]].astype('int')))

<class 'pandas.Series'>
<class 'pandas.Series'>
<class 'pandas.DataFrame'>
<class 'pandas.DataFrame'>