In [1]:
import pandas as pd

landmark = pd.DataFrame(
    {
        "name": ["경복궁", "불국사", "첨성재", "광한루원", "창경궁"],
        "english_name": ["Gyeongbokgung Palace", "bulguksa", "cheomseongdae observatory", "gwanghallu", "Changgyeonggung Palace"],
        "location" : ["서울특별시 종로구 사직로 161", "경상북도 경주시 불국로 385", "경북 경주시 인왕동 839-1", "전라북도 남원시 요천로 1449", "서울특별시 종로구 창경궁로 185"],
    }
)

In [2]:
landmark['name_upper'] = landmark['english_name'].str.upper()
landmark['name_lower'] = landmark['english_name'].str.lower()

landmark[['english_name','name_upper', 'name_lower']]

,english_name,name_upper,name_lower
0,Gyeongbokgung Palace,GYEONGBOKGUNG PALACE,gyeongbokgung palace
1,bulguksa,BULGUKSA,bulguksa
2,cheomseongdae observatory,CHEOMSEONGDAE OBSERVATORY,cheomseongdae observatory
3,gwanghallu,GWANGHALLU,gwanghallu
4,Changgyeonggung Palace,CHANGGYEONGGUNG PALACE,changgyeonggung palace

In [3]:
landmark['name_capitalize'] = landmark['english_name'].str.capitalize()
landmark['name_title'] = landmark['english_name'].str.title()

landmark[['english_name','name_capitalize', 'name_title']]

,english_name,name_capitalize,name_title
0,Gyeongbokgung Palace,Gyeongbokgung palace,Gyeongbokgung Palace
1,bulguksa,Bulguksa,Bulguksa
2,cheomseongdae observatory,Cheomseongdae observatory,Cheomseongdae Observatory
3,gwanghallu,Gwanghallu,Gwanghallu
4,Changgyeonggung Palace,Changgyeonggung palace,Changgyeonggung Palace

In [4]:
landmark['location'].str[3:6]

0    별시
1    도 경
2    경주시
3    도 남
4    별시
Name: location, dtype: str

In [5]:
series_split = landmark['location'].str.split()
series_split

0     [서울특별시, 종로구, 사직로, 161]
1      [경상북도, 경주시, 불국로, 385]
2      [경북, 경주시, 인왕동, 839-1]
3     [전라북도, 남원시, 요천로, 1449]
4    [서울특별시, 종로구, 창경궁로, 185]
Name: location, dtype: object

In [6]:
print(type(series_split))
landmark['location'].str.split().str.get(0)

<class 'pandas.Series'>

0    서울특별시
1     경상북도
2       경북
3     전라북도
4    서울특별시
Name: location, dtype: object

In [7]:
landmark['location'].str.split(" ", expand=True)

       0    1     2      3
0  서울특별시  종로구   사직로    161
1   경상북도  경주시   불국로    385
2     경북  경주시   인왕동  839-1
3   전라북도  남원시   요천로   1449
4  서울특별시  종로구  창경궁로    185

In [8]:
landmark['name_replace'] = landmark['english_name'].str.replace(" ", "_")

landmark['simple_locatoin'] = landmark['location'].str.replace("서울특별시", "서울").str.replace("경상북도", "경북").str.replace("전라북도", "전북").replace("경상북도", "경북")
landmark[['simple_locatoin', 'name_replace']]

    simple_locatoin               name_replace
0    서울 종로구 사직로 161       Gyeongbokgung_Palace
1    경북 경주시 불국로 385                   bulguksa
2  경북 경주시 인왕동 839-1  cheomseongdae_observatory
3   전북 남원시 요천로 1449                 gwanghallu
4   서울 종로구 창경궁로 185     Changgyeonggung_Palace

In [9]:
landmark["detailed address"] = landmark["location"].str.extract("(경주)")
landmark[["detailed address", "location"]]

  detailed address            location
0              NaN   서울특별시 종로구 사직로 161
1               경주    경상북도 경주시 불국로 385
2               경주    경북 경주시 인왕동 839-1
3              NaN   전라북도 남원시 요천로 1449
4              NaN  서울특별시 종로구 창경궁로 185

In [10]:
landmark["detailed address"] = landmark["location"].str.extract("(경주|서울)")
landmark[["detailed address", "location"]]

  detailed address            location
0               서울   서울특별시 종로구 사직로 161
1               경주    경상북도 경주시 불국로 385
2               경주    경북 경주시 인왕동 839-1
3              NaN   전라북도 남원시 요천로 1449
4               서울  서울특별시 종로구 창경궁로 185

In [11]:
landmark["detailed address"] = landmark["location"].str.extract("(\d+-?\d+)")
landmark[["detailed address", "location"]]

  detailed address            location
0              161   서울특별시 종로구 사직로 161
1              385    경상북도 경주시 불국로 385
2            839-1    경북 경주시 인왕동 839-1
3             1449   전라북도 남원시 요천로 1449
4              185  서울특별시 종로구 창경궁로 185

In [12]:
landmark["is_palace"] = landmark["english_name"].str.contains("Palace", case=True)
landmark[["english_name", "is_palace"]]

                english_name  is_palace
0       Gyeongbokgung Palace       True
1                   bulguksa      False
2  cheomseongdae observatory      False
3                 gwanghallu      False
4     Changgyeonggung Palace       True

In [13]:
landmark['location'].str.startswith("서울")

0     True
1    False
2    False
3    False
4     True
Name: location, dtype: bool

In [14]:
landmark['location'].str.endswith("1")

0     True
1    False
2     True
3    False
4    False
Name: location, dtype: bool