In [1]:
import pandas as pd

landmark = pd.DataFrame(
    {
        "name": [" 경복궁 ", "불국사", " 첨성재", "광한루원 ", " 창경궁"],
        "english_name": [" Gyeongbokgung Palace ", "bulguksa", "cheomseongdae observatory", " gwanghallu ", "Changgyeonggung Palace "],
        "location" : [" 서울특별시 종로구 사직로 161 ", "경북 경주시 불국로 385", "경북 경주시 인왕동 839-1" , " 전북 남원시 요천로 1449", "서울특별시 종로구 창경궁로 185"]
    }
)
landmark

    name               english_name             location
0   경복궁       Gyeongbokgung Palace    서울특별시 종로구 사직로 161
1    불국사                   bulguksa       경북 경주시 불국로 385
2    첨성재  cheomseongdae observatory     경북 경주시 인왕동 839-1
3  광한루원                 gwanghallu       전북 남원시 요천로 1449
4    창경궁    Changgyeonggung Palace    서울특별시 종로구 창경궁로 185

In [2]:
landmark['name'] = landmark['name'].str.strip()
landmark['english_name'] = landmark['english_name'].str.strip()
landmark['location'] = landmark['location'].str.strip()

landmark

   name               english_name            location
0   경복궁       Gyeongbokgung Palace   서울특별시 종로구 사직로 161
1   불국사                   bulguksa      경북 경주시 불국로 385
2   첨성재  cheomseongdae observatory    경북 경주시 인왕동 839-1
3  광한루원                 gwanghallu     전북 남원시 요천로 1449
4   창경궁     Changgyeonggung Palace  서울특별시 종로구 창경궁로 185

In [3]:
landmark['name'] = landmark['name'].str.lstrip(" 경")
landmark['english_name'] = landmark['english_name'].str.rstrip("e ")
landmark

   name               english_name            location
0    복궁        Gyeongbokgung Palac   서울특별시 종로구 사직로 161
1   불국사                   bulguksa      경북 경주시 불국로 385
2   첨성재  cheomseongdae observatory    경북 경주시 인왕동 839-1
3  광한루원                 gwanghallu     전북 남원시 요천로 1449
4   창경궁      Changgyeonggung Palac  서울특별시 종로구 창경궁로 185