In [31]:
from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()
iris = pd.DataFrame(iris.data, columns=iris.feature_names)
print(iris[1:4])

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2

In [32]:
iris['sepal length (cm)'].head(4)

0    5.1
1    4.9
2    4.7
3    4.6
Name: sepal length (cm), dtype: float64

In [33]:
iris[['sepal width (cm)', 'sepal length (cm)']].head(4)

   sepal width (cm)  sepal length (cm)
0               3.5                5.1
1               3.0                4.9
2               3.2                4.7
3               3.1                4.6

In [34]:
iris.iloc[0:4]

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2

In [35]:
iris.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='str')

In [36]:
iris.iloc[[0,1,3,5], 2:4]

   petal length (cm)  petal width (cm)
0                1.4               0.2
1                1.4               0.2
3                1.5               0.2
5                1.7               0.4

In [37]:
iris.iloc[:, [True, False, True, False]].head(4)

   sepal length (cm)  petal length (cm)
0                5.1                1.4
1                4.9                1.4
2                4.7                1.3
3                4.6                1.5

In [38]:
iris.iloc[0,0]

np.float64(5.1)

In [39]:
iris.loc[0:3]

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2

In [40]:
iris.loc[0:3, 'sepal length (cm)':'petal length (cm)']

   sepal length (cm)  sepal width (cm)  petal length (cm)
0                5.1               3.5                1.4
1                4.9               3.0                1.4
2                4.7               3.2                1.3
3                4.6               3.1                1.5

In [41]:
score = pd.DataFrame({"국어": [90, 80, 70], "영어": [85, 75, 65], "수학": [95, 85, 75]}, index=['홍길동', '김철수', '이영희'])
score.loc['홍길동', '영어'] = 100
score['국어'] = score['국어'] - 3
score

     국어   영어  수학
홍길동  87  100  95
김철수  77   75  85
이영희  67   65  75

In [42]:
new_students = pd.DataFrame({"국어": [88, 78], "영어": [82, 72], "수학": [92, 82]}, index=['박영수', '최민수'])
score = pd.concat([score, new_students])
# score = score.append(new_students) # append는 pandas 1.4.0 이후로 deprecated 되었음
score

     국어   영어  수학
홍길동  87  100  95
김철수  77   75  85
이영희  67   65  75
박영수  88   82  92
최민수  78   72  82

In [43]:
another_student1 = pd.DataFrame({"국어": [85], "영어": [80], "수학": [90]}, index=['김영수'])
score = pd.concat([score, another_student1])
score

     국어   영어  수학
홍길동  87  100  95
김철수  77   75  85
이영희  67   65  75
박영수  88   82  92
최민수  78   72  82
김영수  85   80  90

In [44]:
science_score =[85, 75, 65, 80, 70, 20]
score['과학'] = science_score
score['학년'] = 1
score

     국어   영어  수학  과학  학년
홍길동  87  100  95  85   1
김철수  77   75  85  75   1
이영희  67   65  75  65   1
박영수  88   82  92  80   1
최민수  78   72  82  70   1
김영수  85   80  90  20   1

In [45]:
social_score = pd.DataFrame({"사회": [80, 70, 60, 75, 65, 30]}, index=score.index)
score = pd.concat([score, social_score], axis=1)
score

     국어   영어  수학  과학  학년  사회
홍길동  87  100  95  85   1  80
김철수  77   75  85  75   1  70
이영희  67   65  75  65   1  60
박영수  88   82  92  80   1  75
최민수  78   72  82  70   1  65
김영수  85   80  90  20   1  30

In [46]:
magic_score = pd.Series([90, 80, 70, 85, 75, 25], index=score.index)
score['마법'] = magic_score
score

     국어   영어  수학  과학  학년  사회  마법
홍길동  87  100  95  85   1  80  90
김철수  77   75  85  75   1  70  80
이영희  67   65  75  65   1  60  70
박영수  88   82  92  80   1  75  85
최민수  78   72  82  70   1  65  75
김영수  85   80  90  20   1  30  25

In [47]:
score['총점'] = score.sum(axis=1) -1
score

     국어   영어  수학  과학  학년  사회  마법   총점
홍길동  87  100  95  85   1  80  90  537
김철수  77   75  85  75   1  70  80  462
이영희  67   65  75  65   1  60  70  402
박영수  88   82  92  80   1  75  85  502
최민수  78   72  82  70   1  65  75  442
김영수  85   80  90  20   1  30  25  330

In [48]:
score.drop('홍길동', inplace=True)
score.drop('마법', inplace=True, axis=1)
score

     국어  영어  수학  과학  학년  사회   총점
김철수  77  75  85  75   1  70  462
이영희  67  65  75  65   1  60  402
박영수  88  82  92  80   1  75  502
최민수  78  72  82  70   1  65  442
김영수  85  80  90  20   1  30  330