In [1]:
import pandas as pd
students = pd.DataFrame({'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'], 'math': [85, None, 78, 90, 88], 'english': [90, None, 80, None, 92]})
students[students['name'] == 'Alice']

    name  math  english
0  Alice  85.0     90.0

In [2]:
print(students['name'] == 'Alice')
print(type(students['name'] == 'Alice'))

0     True
1    False
2    False
3    False
4    False
Name: name, dtype: bool
<class 'pandas.Series'>

In [3]:
students[(students['math'] >= 80) & (students['english'] > 80)]

    name  math  english
0  Alice  85.0     90.0
4    Eve  88.0     92.0

In [4]:
students.loc[6, 'name':'english'] = ['Frank', 82, 88]
students.loc[(students['english'] > 90) & (students['math'] > 85), 'P/F'] = 'Pass'
students.loc[students['P/F'] != 'Pass', 'P/F'] = 'Fail'
print(students)

      name  math  english   P/F
0    Alice  85.0     90.0  Fail
1      Bob   NaN      NaN  Fail
2  Charlie  78.0     80.0  Fail
3    David  90.0      NaN  Fail
4      Eve  88.0     92.0  Pass
6    Frank  82.0     88.0  Fail

In [5]:
import numpy as np
conditions = [(students['math'] >= 90) & (students['english'] >= 90), (students['math'] >= 80) & (students['english'] >= 80)]
choice_list = ['Excellent', 'Good']
students['Grade'] = np.select(conditions, choice_list, default='Enhancing')
print(students)

      name  math  english   P/F      Grade
0    Alice  85.0     90.0  Fail       Good
1      Bob   NaN      NaN  Fail  Enhancing
2  Charlie  78.0     80.0  Fail  Enhancing
3    David  90.0      NaN  Fail  Enhancing
4      Eve  88.0     92.0  Pass       Good
6    Frank  82.0     88.0  Fail       Good

In [6]:
# 작동방식
print(conditions[0])
print(type(conditions[0]))
print(np.select(conditions, choice_list, default='Enhancing'))

0    False
1    False
2    False
3    False
4    False
6    False
dtype: bool
<class 'pandas.Series'>
['Good' 'Enhancing' 'Enhancing' 'Enhancing' 'Good' 'Good']

In [7]:
print(students.isna())
print(students.notna())

    name   math  english    P/F  Grade
0  False  False    False  False  False
1  False   True     True  False  False
2  False  False    False  False  False
3  False  False     True  False  False
4  False  False    False  False  False
6  False  False    False  False  False
   name   math  english   P/F  Grade
0  True   True     True  True   True
1  True  False    False  True   True
2  True   True     True  True   True
3  True   True    False  True   True
4  True   True     True  True   True
6  True   True     True  True   True

In [8]:
print(students.isna().sum())
print(students.notna().sum())

name       0
math       1
english    2
P/F        0
Grade      0
dtype: int64
name       6
math       5
english    4
P/F        6
Grade      6
dtype: int64

In [9]:
students.dropna()

      name  math  english   P/F      Grade
0    Alice  85.0     90.0  Fail       Good
2  Charlie  78.0     80.0  Fail  Enhancing
4      Eve  88.0     92.0  Pass       Good
6    Frank  82.0     88.0  Fail       Good

In [10]:
students.dropna(axis=1)

      name   P/F      Grade
0    Alice  Fail       Good
1      Bob  Fail  Enhancing
2  Charlie  Fail  Enhancing
3    David  Fail  Enhancing
4      Eve  Pass       Good
6    Frank  Fail       Good

In [11]:
students.dropna(subset=['math'])

      name  math  english   P/F      Grade
0    Alice  85.0     90.0  Fail       Good
2  Charlie  78.0     80.0  Fail  Enhancing
3    David  90.0      NaN  Fail  Enhancing
4      Eve  88.0     92.0  Pass       Good
6    Frank  82.0     88.0  Fail       Good

In [12]:
students.dropna(thresh=4)

      name  math  english   P/F      Grade
0    Alice  85.0     90.0  Fail       Good
2  Charlie  78.0     80.0  Fail  Enhancing
3    David  90.0      NaN  Fail  Enhancing
4      Eve  88.0     92.0  Pass       Good
6    Frank  82.0     88.0  Fail       Good

In [13]:
students.fillna(0)

      name  math  english   P/F      Grade
0    Alice  85.0     90.0  Fail       Good
1      Bob   0.0      0.0  Fail  Enhancing
2  Charlie  78.0     80.0  Fail  Enhancing
3    David  90.0      0.0  Fail  Enhancing
4      Eve  88.0     92.0  Pass       Good
6    Frank  82.0     88.0  Fail       Good

In [14]:
students.fillna(students.mean(numeric_only=True))

      name  math  english   P/F      Grade
0    Alice  85.0     90.0  Fail       Good
1      Bob  84.6     87.5  Fail  Enhancing
2  Charlie  78.0     80.0  Fail  Enhancing
3    David  90.0     87.5  Fail  Enhancing
4      Eve  88.0     92.0  Pass       Good
6    Frank  82.0     88.0  Fail       Good

In [15]:
#짚고 넘어가기
print(students.mean(numeric_only=True))
#print(students.mean()) #numeric_only=True 옵션이 없으면 오류가 발생한다. mean() 함수는 숫자형 데이터에 대해서만 평균을 계산할 수 있기 때문이다. students 데이터프레임에는 'name' 열이 문자열로 되어 있기 때문에, mean() 함수를 호출할 때 numeric_only=True 옵션을 사용하여 숫자형 열에 대해서만 평균을 계산하도록 지정해야 한다.
print(type(students.mean(numeric_only=True)))

math       84.6
english    87.5
dtype: float64
<class 'pandas.Series'>

In [16]:
students['math'] = students['math'].fillna(students['math'].mean(numeric_only=True)) 
students['english'] = students['english'].fillna(0)
print(students)

      name  math  english   P/F      Grade
0    Alice  85.0     90.0  Fail       Good
1      Bob  84.6      0.0  Fail  Enhancing
2  Charlie  78.0     80.0  Fail  Enhancing
3    David  90.0      0.0  Fail  Enhancing
4      Eve  88.0     92.0  Pass       Good
6    Frank  82.0     88.0  Fail       Good

In [17]:
#students.fillna(method='ffill', inplace=True) #ffill은 forward fill의 약자로, 결측값을 이전 값으로 채우는 방법입니다. inplace=True 옵션을 사용하면 원본 데이터프레임이 수정됩니다. 따라서 students 데이터프레임에서 결측값이 있는 경우, 해당 결측값이 바로 이전 행의 값으로 채워지게 됩니다.
# TypeError : unsupported operand type(s) for -: 'str' and 'str'
students.ffill(inplace=True) #ffill은 forward fill의 약자로, 결측값을 이전 값으로 채우는 방법입니다. inplace=True 옵션을 사용하면 원본 데이터프레임이 수정됩니다. 따라서 students 데이터프레임에서 결측값이 있는 경우, 해당 결측값이 바로 이전 행의 값으로 채워지게 됩니다.

      name  math  english   P/F      Grade
0    Alice  85.0     90.0  Fail       Good
1      Bob  84.6      0.0  Fail  Enhancing
2  Charlie  78.0     80.0  Fail  Enhancing
3    David  90.0      0.0  Fail  Enhancing
4      Eve  88.0     92.0  Pass       Good
6    Frank  82.0     88.0  Fail       Good

In [18]:
set(students['name'])
print(type(set(students['name'])))

<class 'set'>

In [19]:
students['math'].drop_duplicates()

0    85.0
1    84.6
2    78.0
3    90.0
4    88.0
6    82.0
Name: math, dtype: float64