In [1]:
import pandas as pd
from sklearn.datasets import load_iris

iris = load_iris()
iris = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris.sort_index(ascending=False, inplace=True)
iris.head()

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
149                5.9               3.0                5.1               1.8
148                6.2               3.4                5.4               2.3
147                6.5               3.0                5.2               2.0
146                6.3               2.5                5.0               1.9
145                6.7               3.0                5.2               2.3

In [2]:
iris.sort_index(axis=1, ascending=True, inplace=True)
iris.head()

     petal length (cm)  petal width (cm)  sepal length (cm)  sepal width (cm)
149                5.1               1.8                5.9               3.0
148                5.4               2.3                6.2               3.4
147                5.2               2.0                6.5               3.0
146                5.0               1.9                6.3               2.5
145                5.2               2.3                6.7               3.0

In [3]:
iris.sort_values(by="petal length (cm)")

     petal length (cm)  petal width (cm)  sepal length (cm)  sepal width (cm)
22                 1.0               0.2                4.6               3.6
13                 1.1               0.1                4.3               3.0
14                 1.2               0.2                5.8               4.0
35                 1.2               0.2                5.0               3.2
41                 1.3               0.3                4.5               2.3
..                 ...               ...                ...               ...
131                6.4               2.0                7.9               3.8
105                6.6               2.1                7.6               3.0
122                6.7               2.0                7.7               2.8
117                6.7               2.2                7.7               3.8
118                6.9               2.3                7.7               2.6

[150 rows x 4 columns]

In [4]:
iris.sort_values(by=["petal length (cm)", "petal width (cm)"], ascending=[True, False])

     petal length (cm)  petal width (cm)  sepal length (cm)  sepal width (cm)
22                 1.0               0.2                4.6               3.6
13                 1.1               0.1                4.3               3.0
35                 1.2               0.2                5.0               3.2
14                 1.2               0.2                5.8               4.0
16                 1.3               0.4                5.4               3.9
..                 ...               ...                ...               ...
131                6.4               2.0                7.9               3.8
105                6.6               2.1                7.6               3.0
117                6.7               2.2                7.7               3.8
122                6.7               2.0                7.7               2.8
118                6.9               2.3                7.7               2.6

[150 rows x 4 columns]