In [1]:
import pandas as pd

In [2]:
product = pd.DataFrame({"상품코드": ["G1", "G2", "G3", "G4"], "상품명": ["노트북", "스마트폰", "태블릿"," 모니터"]})
orders = pd.DataFrame({"주문번호": [1001, 1002, 1003, 1004, 1005], "상품코드": ["G4", "G3", "G1", "G3", "G5"], "수량": [1, 4, 2, 2, 3]})
print(orders.merge(product, on="상품코드", how="inner"))

   주문번호 상품코드  수량   상품명
0  1001   G4   1   모니터
1  1002   G3   4   태블릿
2  1003   G1   2   노트북
3  1004   G3   2   태블릿

In [3]:
orders.merge(product, on="상품코드", how="outer")

     주문번호 상품코드   수량   상품명
0  1003.0   G1  2.0   노트북
1     NaN   G2  NaN  스마트폰
2  1002.0   G3  4.0   태블릿
3  1004.0   G3  2.0   태블릿
4  1001.0   G4  1.0   모니터
5  1005.0   G5  3.0   NaN

In [4]:
orders.merge(product, on="상품코드", how="left")

   주문번호 상품코드  수량   상품명
0  1001   G4   1   모니터
1  1002   G3   4   태블릿
2  1003   G1   2   노트북
3  1004   G3   2   태블릿
4  1005   G5   3   NaN

In [5]:
orders.merge(product, on="상품코드", how="right")

     주문번호 상품코드   수량   상품명
0  1003.0   G1  2.0   노트북
1     NaN   G2  NaN  스마트폰
2  1002.0   G3  4.0   태블릿
3  1004.0   G3  2.0   태블릿
4  1001.0   G4  1.0   모니터