In [1]:
import pandas as pd
scores = {"학년": [1,1,1,1,2,2],
          '반': ["A","A","B","B","C","C"],
          "성별": ["남","여","남","여","남","여"],
          "점수": [90, 85, 80, 95, 88, 92]}
df = pd.DataFrame(scores)
df

   학년  반 성별  점수
0   1  A  남  90
1   1  A  여  85
2   1  B  남  80
3   1  B  여  95
4   2  C  남  88
5   2  C  여  92

In [2]:
df = df.pivot_table(index=["학년", "반"], columns="성별", values="점수")
df

성별       남     여
학년 반
1  A  90.0  85.0
   B  80.0  95.0
2  C  88.0  92.0

In [3]:
df.reset_index()

성별  학년  반     남     여
0    1  A  90.0  85.0
1    1  B  80.0  95.0
2    2  C  88.0  92.0

In [4]:
df.reset_index().melt(id_vars=["학년", "반"], var_name="성별", value_name="점수")

   학년  반 성별    점수
0   1  A  남  90.0
1   1  B  남  80.0
2   2  C  남  88.0
3   1  A  여  85.0
4   1  B  여  95.0
5   2  C  여  92.0

In [5]:
import numpy as np

df.apply(np.sqrt, axis=0)

성별           남         여
학년 반
1  A  9.486833  9.219544
   B  8.944272  9.746794
2  C  9.380832  9.591663

In [6]:
df.apply(np.max, axis=0)

성별
남    90.0
여    95.0
dtype: float64

In [7]:
df.apply(np.max, axis=1)

학년  반
1   A    90.0
    B    95.0
2   C    92.0
dtype: float64

In [9]:
def plus_five(val):
    return val + 5
df.apply(plus_five, axis=0)

성별       남      여
학년 반
1  A  95.0   90.0
   B  85.0  100.0
2  C  93.0   97.0

In [13]:
def class_avg(df):
    return int((df["남"] + df["여"]) / 2)

df.apply(class_avg, axis=1)

학년  반
1   A    87
    B    87
2   C    90
dtype: int64

In [15]:
df['남'].map(lambda x: x + 5)

학년  반
1   A    95.0
    B    85.0
2   C    93.0
Name: 남, dtype: float64