In [1]:
import pandas as pd

In [2]:
product = pd.DataFrame({
    "상품코드": ["G1", "G2", "G3", "G4"],
    "상품명": ["우유", "감자", "빵", "치킨"]
})

sale = pd.DataFrame({
    "주문번호": [1001, 1002, 1002, 1003, 1004],
    "상품코드": ["G4", "G3", "G1", "G3", "G5"],
    "주문수량": [1, 4, 2, 2, 3]
})

In [3]:
print(product)
print(sale)

  상품코드 상품명
0   G1  우유
1   G2  감자
2   G3   빵
3   G4  치킨
   주문번호 상품코드  주문수량
0  1001   G4     1
1  1002   G3     4
2  1002   G1     2
3  1003   G3     2
4  1004   G5     3

In [7]:
sale.merge(product, on="상품코드", how="inner", sort=False)

   주문번호 상품코드  주문수량 상품명
0  1001   G4     1  치킨
1  1002   G3     4   빵
2  1002   G1     2  우유
3  1003   G3     2   빵

In [9]:
sale.merge(product, on="상품코드", how="outer", sort=False)

     주문번호 상품코드  주문수량  상품명
0  1002.0   G1   2.0   우유
1     NaN   G2   NaN   감자
2  1002.0   G3   4.0    빵
3  1003.0   G3   2.0    빵
4  1001.0   G4   1.0   치킨
5  1004.0   G5   3.0  NaN

In [10]:
sale.merge(product, left_on="상품코드", right_on="상품코드", how="left", sort=False)

   주문번호 상품코드  주문수량  상품명
0  1001   G4     1   치킨
1  1002   G3     4    빵
2  1002   G1     2   우유
3  1003   G3     2    빵
4  1004   G5     3  NaN

In [11]:
sale.merge(product, left_on="상품코드", right_on="상품코드", how="right", sort=False)

     주문번호 상품코드  주문수량 상품명
0  1002.0   G1   2.0  우유
1     NaN   G2   NaN  감자
2  1002.0   G3   4.0   빵
3  1003.0   G3   2.0   빵
4  1001.0   G4   1.0  치킨