In [1]:
import pandas as pd

In [11]:
health = pd.DataFrame({
    "연도": [2017, 2018, 2019, 2020, 2021, 2022],
    "키": [160, 162, 165, None, None, 166],
    "몸무게": [53, 52, None, 50, 51, 54],
    "시력": [1.2, None, 1.2, 1.2, 1.1, 0.8],
    "병결": [None, None, None, 2, None, 1]
})
health

In [3]:
health.fillna(0)

     연도      키   몸무게   시력   병결
0  2017  160.0  53.0  1.2  NaN
1  2018  162.0  52.0  NaN  NaN
2  2019  165.0   NaN  1.2  NaN
3  2020    NaN  50.0  1.2  2.0
4  2021    NaN  51.0  1.1  NaN
5  2022  166.0  54.0  0.8  1.0

In [4]:
health.fillna(health.mean())

     연도      키   몸무게   시력   병결
0  2017  160.0  53.0  1.2  0.0
1  2018  162.0  52.0  0.0  0.0
2  2019  165.0   0.0  1.2  0.0
3  2020    0.0  50.0  1.2  2.0
4  2021    0.0  51.0  1.1  0.0
5  2022  166.0  54.0  0.8  1.0

In [6]:
health["병결"] = health["병결"].fillna(0)
health

     연도      키   몸무게   시력   병결
0  2017  160.0  53.0  1.2  0.0
1  2018  162.0  52.0  NaN  0.0
2  2019  165.0   NaN  1.2  0.0
3  2020    NaN  50.0  1.2  2.0
4  2021    NaN  51.0  1.1  0.0
5  2022  166.0  54.0  0.8  1.0

In [10]:
health["몸무게"].mean()

np.float64(52.0)

In [7]:
health["몸무게"] = health["몸무게"].fillna(health["몸무게"].mean())
health

     연도      키   몸무게   시력   병결
0  2017  160.0  53.0  1.2  0.0
1  2018  162.0  52.0  NaN  0.0
2  2019  165.0  52.0  1.2  0.0
3  2020    NaN  50.0  1.2  2.0
4  2021    NaN  51.0  1.1  0.0
5  2022  166.0  54.0  0.8  1.0

In [ ]:
print(health["몸무게"].mean())
print(type(health["몸무게"].mean()))

In [16]:
health

     연도      키   몸무게   시력   병결
0  2017  160.0  53.0  1.2  NaN
1  2018  162.0  52.0  NaN  NaN
2  2019  165.0   NaN  1.2  NaN
3  2020    NaN  50.0  1.2  2.0
4  2021    NaN  51.0  1.1  NaN
5  2022  166.0  54.0  0.8  1.0

In [15]:
health.ffill()

     연도      키   몸무게   시력   병결
0  2017  160.0  53.0  1.2  NaN
1  2018  162.0  52.0  1.2  NaN
2  2019  165.0  52.0  1.2  NaN
3  2020  165.0  50.0  1.2  2.0
4  2021  165.0  51.0  1.1  2.0
5  2022  166.0  54.0  0.8  1.0

In [17]:
health.bfill()

     연도      키   몸무게   시력   병결
0  2017  160.0  53.0  1.2  2.0
1  2018  162.0  52.0  1.2  2.0
2  2019  165.0  50.0  1.2  2.0
3  2020  166.0  50.0  1.2  2.0
4  2021  166.0  51.0  1.1  1.0
5  2022  166.0  54.0  0.8  1.0

In [18]:
health["키"].drop_duplicates()

0    160.0
1    162.0
2    165.0
3      NaN
5    166.0
Name: 키, dtype: float64

In [19]:
print(set(health["키"]))
print(type(set(health["키"])))

{160.0, 162.0, 165.0, 166.0, nan, nan}
<class 'set'>

In [22]:
health.bfill(inplace=True)
health[["시력", "병결"]].drop_duplicates()

    시력   병결
0  1.2  2.0
4  1.1  2.0
5  0.8  1.0