In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.datasets import load_wine

In [2]:
np.array([[[]]])

array([], shape=(1, 1, 0), dtype=float64)

In [6]:
df = pd.DataFrame(data=[["kor", 70],["math", "80"]], columns=["class", "score"])
print(df)

  class score
0   kor    70
1  math   80-

In [16]:
df = pd.DataFrame({"class": ["LLM활용", "LLM학습"], "수준":["중","상"]})
print(df)

   class 수준
0  LLM활용  중
1  LLM학습  상

In [8]:
iris = load_iris()
print(type(iris))
iris = pd.DataFrame(iris.data, columns=iris.feature_names)
print(type(iris))
print(iris)

<class 'sklearn.utils._bunch.Bunch'>
<class 'pandas.core.frame.DataFrame'>
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [9]:
print(iris.head())
print(iris.tail())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

In [10]:
print(iris.head(8))
print(iris.tail(8))

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
5                5.4               3.9                1.7               0.4
6                4.6               3.4                1.4               0.3
7                5.0               3.4                1.5               0.2
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
142                5.8               2.7                5.1               1.9
143                6.8               3.2                5.9               2.3
144                6.7               3.3                5.7               2.5
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

In [11]:
print(iris.info())
print(len(iris))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB
None
150

In [17]:
print(df.index)
# print(list(df.index))
# df.index=["A", "B"]
# print(df.index)
# print(df)

RangeIndex(start=0, stop=2, step=1)

In [18]:
print(list(df.index))

[0, 1]

In [19]:
df.index=["A", "B"]
print(df.index)

Index(['A', 'B'], dtype='object')

In [20]:
print(df)

   class 수준
A  LLM활용  중
B  LLM학습  상

In [21]:
df.set_index("class", drop=True, append=False, inplace=True)
print(df)

      수준
class
LLM활용  중
LLM학습  상

In [22]:
df.reset_index(drop=False, inplace=True)
print(df)

   class 수준
0  LLM활용  중
1  LLM학습  상

In [23]:
print(iris.columns)

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [24]:
iris.columns = ["sepal length", "sepal width", "petal length", "petal width"]
print(iris.columns)
print(iris)

Index(['sepal length', 'sepal width', 'petal length', 'petal width'], dtype='object')
     sepal length  sepal width  petal length  petal width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [32]:
# print(iris.columns)
# print(type(iris.columns))
# print(iris.columns.str)
# print(type(iris.columns.str))
# print(iris.columns.str.replace)
# print(type(iris.columns.str.replace))

iris.columns = iris.columns.str.replace(" ", "_")
print(iris.head(3))

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2

In [33]:
iris.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
dtype: object

In [35]:
iris['sepal_width'].astype('int')

0      3
1      3
2      3
3      3
4      3
      ..
145    3
146    2
147    3
148    3
149    3
Name: sepal_width, Length: 150, dtype: int64