In [1]:
import pandas as pd
from sklearn.datasets import load_iris
iris = load_iris()
iris = pd.DataFrame(iris.data, columns= iris.feature_names)

In [2]:
iris

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [3]:
iris.columns = ["sep_len", "sep_wid", "pet_len", "pet_wid"]

In [4]:
iris

     sep_len  sep_wid  pet_len  pet_wid
0        5.1      3.5      1.4      0.2
1        4.9      3.0      1.4      0.2
2        4.7      3.2      1.3      0.2
3        4.6      3.1      1.5      0.2
4        5.0      3.6      1.4      0.2
..       ...      ...      ...      ...
145      6.7      3.0      5.2      2.3
146      6.3      2.5      5.0      1.9
147      6.5      3.0      5.2      2.0
148      6.2      3.4      5.4      2.3
149      5.9      3.0      5.1      1.8

[150 rows x 4 columns]

In [5]:
iris.sort_index(axis=1, ascending=True, inplace=True)
print(iris)

     pet_len  pet_wid  sep_len  sep_wid
0        1.4      0.2      5.1      3.5
1        1.4      0.2      4.9      3.0
2        1.3      0.2      4.7      3.2
3        1.5      0.2      4.6      3.1
4        1.4      0.2      5.0      3.6
..       ...      ...      ...      ...
145      5.2      2.3      6.7      3.0
146      5.0      1.9      6.3      2.5
147      5.2      2.0      6.5      3.0
148      5.4      2.3      6.2      3.4
149      5.1      1.8      5.9      3.0

[150 rows x 4 columns]

In [6]:
iris.sort_values("pet_len")

     pet_len  pet_wid  sep_len  sep_wid
22       1.0      0.2      4.6      3.6
13       1.1      0.1      4.3      3.0
14       1.2      0.2      5.8      4.0
35       1.2      0.2      5.0      3.2
16       1.3      0.4      5.4      3.9
..       ...      ...      ...      ...
131      6.4      2.0      7.9      3.8
105      6.6      2.1      7.6      3.0
117      6.7      2.2      7.7      3.8
122      6.7      2.0      7.7      2.8
118      6.9      2.3      7.7      2.6

[150 rows x 4 columns]

In [7]:
iris.sort_values(["pet_len", "sep_len"], ascending=False)

     pet_len  pet_wid  sep_len  sep_wid
118      6.9      2.3      7.7      2.6
117      6.7      2.2      7.7      3.8
122      6.7      2.0      7.7      2.8
105      6.6      2.1      7.6      3.0
131      6.4      2.0      7.9      3.8
..       ...      ...      ...      ...
42       1.3      0.2      4.4      3.2
14       1.2      0.2      5.8      4.0
35       1.2      0.2      5.0      3.2
13       1.1      0.1      4.3      3.0
22       1.0      0.2      4.6      3.6

[150 rows x 4 columns]