In [1]:
import pandas as pd
import numpy as np

students = pd.DataFrame({"이름": ["장화", "홍련", "콩쥐", "팥쥐", "햇님", "달님"],
"국어": [70, 85, None, 100, None, 85],
"수학": [65, 100, 80, 95, None, 70]})

In [8]:
# students["이름"] == "장화"
# type(students["이름"] == "장화")
# students[students["이름"] == "장화"]
students[[True,False,False,False,False,False]]

   이름    국어    수학
0  장화  70.0  65.0

In [15]:
# students[(students["국어"] >= 80) & (students["수학"] >= 80)]
(students["국어"] >= 80) & (students["수학"] >= 80)

0    False
1     True
2    False
3     True
4    False
5    False
dtype: bool

In [17]:
students.loc[6] = ["별님", 50, 60]
students

   이름     국어     수학
0  장화   70.0   65.0
1  홍련   85.0  100.0
2  콩쥐    NaN   80.0
3  팥쥐  100.0   95.0
4  햇님    NaN    NaN
5  달님   85.0   70.0
6  별님   50.0   60.0

In [19]:
students.loc[(students["국어"]>=80)&(students["수학"]>=80), "합격"] = "Pass"
students

   이름     국어     수학    합격
0  장화   70.0   65.0   NaN
1  홍련   85.0  100.0  Pass
2  콩쥐    NaN   80.0   NaN
3  팥쥐  100.0   95.0  Pass
4  햇님    NaN    NaN   NaN
5  달님   85.0   70.0   NaN
6  별님   50.0   60.0   NaN

In [20]:
students.loc[students["합격"] != "Pass", "합격"] = "Fail"
students

   이름     국어     수학    합격
0  장화   70.0   65.0  Fail
1  홍련   85.0  100.0  Pass
2  콩쥐    NaN   80.0  Fail
3  팥쥐  100.0   95.0  Pass
4  햇님    NaN    NaN  Fail
5  달님   85.0   70.0  Fail
6  별님   50.0   60.0  Fail

In [26]:
condition_list= [(students["국어"] >= 90),
                 (students["국어"] >= 80) & (students["국어"] < 90),
                 (students["국어"] >= 70) & (students["국어"] < 90)]
choice_list = ["A", "B", "C"]
students["국어등급"] = np.select(condition_list, choice_list, "F")
students

   이름     국어     수학    합격 국어등급
0  장화   70.0   65.0  Fail    C
1  홍련   85.0  100.0  Pass    B
2  콩쥐    NaN   80.0  Fail    F
3  팥쥐  100.0   95.0  Pass    A
4  햇님    NaN    NaN  Fail    F
5  달님   85.0   70.0  Fail    B
6  별님   50.0   60.0  Fail    F

In [27]:
students.isna()

      이름     국어     수학     합격   국어등급
0  False  False  False  False  False
1  False  False  False  False  False
2  False   True  False  False  False
3  False  False  False  False  False
4  False   True   True  False  False
5  False  False  False  False  False
6  False  False  False  False  False

In [28]:
students.isnull()

      이름     국어     수학     합격   국어등급
0  False  False  False  False  False
1  False  False  False  False  False
2  False   True  False  False  False
3  False  False  False  False  False
4  False   True   True  False  False
5  False  False  False  False  False
6  False  False  False  False  False

In [29]:
students.notna()

     이름     국어     수학    합격  국어등급
0  True   True   True  True  True
1  True   True   True  True  True
2  True  False   True  True  True
3  True   True   True  True  True
4  True  False  False  True  True
5  True   True   True  True  True
6  True   True   True  True  True

In [34]:
students["국어"].isna()
# type(students["장화"])

0    False
1    False
2     True
3    False
4     True
5    False
6    False
Name: 국어, dtype: bool

In [35]:
students.isna().sum(0)

이름      0
국어      2
수학      1
합격      0
국어등급    0
dtype: int64

In [37]:
st_nameindex = students.set_index("이름",drop=True)
st_nameindex.isna().sum(1)

이름
장화    0
홍련    0
콩쥐    1
팥쥐    0
햇님    2
달님    0
별님    0
dtype: int64

In [38]:
students.dropna()

   이름     국어     수학    합격 국어등급
0  장화   70.0   65.0  Fail    C
1  홍련   85.0  100.0  Pass    B
3  팥쥐  100.0   95.0  Pass    A
5  달님   85.0   70.0  Fail    B
6  별님   50.0   60.0  Fail    F

In [41]:
students.dropna(axis=1)

   이름    합격 국어등급
0  장화  Fail    C
1  홍련  Pass    B
2  콩쥐  Fail    F
3  팥쥐  Pass    A
4  햇님  Fail    F
5  달님  Fail    B
6  별님  Fail    F

In [43]:
students.dropna(thresh=4)
#햇님만 사라졌다.

   이름     국어     수학    합격 국어등급
0  장화   70.0   65.0  Fail    C
1  홍련   85.0  100.0  Pass    B
2  콩쥐    NaN   80.0  Fail    F
3  팥쥐  100.0   95.0  Pass    A
5  달님   85.0   70.0  Fail    B
6  별님   50.0   60.0  Fail    F