In [5]:
from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()
iris = pd.DataFrame(data=iris.data, columns=iris.feature_names)
print(iris[1:4])

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2

In [6]:
iris.columns = iris.columns.str.replace(" (cm)", "").str.replace(" ", "_")
print(iris)

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [12]:
iris["sepal_length"].head(4)
# iris["sepal_length"][:5]

0    5.1
1    4.9
2    4.7
3    4.6
Name: sepal_length, dtype: float64

In [13]:
# iris.columns
iris[["sepal_length", "sepal_width"]]

     sepal_length  sepal_width
0             5.1          3.5
1             4.9          3.0
2             4.7          3.2
3             4.6          3.1
4             5.0          3.6
..            ...          ...
145           6.7          3.0
146           6.3          2.5
147           6.5          3.0
148           6.2          3.4
149           5.9          3.0

[150 rows x 2 columns]

In [24]:
type(iris.iloc)

pandas.core.indexing._iLocIndexer

In [25]:
type(iris.loc)

pandas.core.indexing._LocIndexer

In [34]:
iris.iloc[:4]
# iris.iloc[:4, :2]
# iris.iloc[2:6, [1,2,3]]
# iris.iloc[2:6, [3,2,1]]
# iris.iloc[2:6, [1,3]]
# iris.iloc[:,[True,True,False,True]]

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2

In [35]:
print(iris.iloc[:3])
print(iris.loc[:3])

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2

In [27]:
iris.loc[[1,20], "sepal_width":"petal_length"]

    sepal_width  petal_length
1           3.0           1.4
20          3.4           1.7

In [44]:
score = pd.DataFrame({"국어": [90, 80], "영어": [10, 10], "수학":[70, 70]}, index = ["장화", "홍련"])
score

    국어  영어  수학
장화  90  10  70
홍련  80  10  70

In [47]:
# score.loc["홍련"] = 100
score.loc["홍련", "영어"] = 100
# score["국어"] = score["국어"] - 5
score["국어"] -= 5
score

    국어   영어  수학
장화  75   10  70
홍련  65  100  70

In [48]:
print(score["국어"])
print(type(score["국어"]))
print(score["국어"]-5)
print(type(score["국어"]-5))
print(score.loc["홍련", "영어"])
print(type(score.loc["홍련", "영어"]))

장화    75
홍련    65
Name: 국어, dtype: int64
<class 'pandas.core.series.Series'>
장화    70
홍련    60
Name: 국어, dtype: int64
<class 'pandas.core.series.Series'>
100
<class 'numpy.int64'>

In [49]:
new_students = pd.DataFrame({"국어": [70, 85], "수학": [65, 100], "영어": [95, 65]}, index=["콩쥐", "팥쥐"])
score = pd.concat([score, new_students])

single_student = pd.Series({"국어": 100, "수학": 100, "영어":100}, name="햇님")

score.loc["햇님"] = single_student

score

     국어   영어   수학
장화   75   10   70
홍련   65  100   70
콩쥐   70   95   65
팥쥐   85   65  100
햇님  100  100  100

In [51]:
single_student = pd.Series({"국어": 100, "수학": 100, "영어":100})

score.loc["달님"] = single_student

score

     국어   영어   수학
장화   75   10   70
홍련   65  100   70
콩쥐   70   95   65
팥쥐   85   65  100
햇님  100  100  100
달님  100  100  100

In [52]:
single_student = pd.Series({"국어": 100, "수학": 100, "영어":100}, name="무명")

score.loc["별님"] = single_student

score

     국어   영어   수학
장화   75   10   70
홍련   65  100   70
콩쥐   70   95   65
팥쥐   85   65  100
햇님  100  100  100
달님  100  100  100
별님  100  100  100

In [54]:
science = [80, 70, 90, 85, 75, 100, 95]
score["과학"] = science

score["학년"] = 1
score

     국어   영어   수학   과학  학년
장화   75   10   70   80   1
홍련   65  100   70   70   1
콩쥐   70   95   65   90   1
팥쥐   85   65  100   85   1
햇님  100  100  100   75   1
달님  100  100  100  100   1
별님  100  100  100   95   1

In [55]:
score["총점"] = score["국어"] + score["수학"] + score["영어"] + score["과학"]
score
# print(type(score["국어"] + score["수학"] + score["영어"] + score["과학"]))

     국어   영어   수학   과학  학년   총점
장화   75   10   70   80   1  235
홍련   65  100   70   70   1  305
콩쥐   70   95   65   90   1  320
팥쥐   85   65  100   85   1  335
햇님  100  100  100   75   1  375
달님  100  100  100  100   1  400
별님  100  100  100   95   1  395

In [65]:
# score[:5]
# score["총점"]
# score[:3]["총점"]
print(type(score))
print(type(score[:3]))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>

In [74]:
print(score.drop(columns=["국어"]))
print(score.drop("장화"))

     영어   수학   과학  학년   총점
장화   10   70   80   1  235
홍련  100   70   70   1  305
콩쥐   95   65   90   1  320
팥쥐   65  100   85   1  335
햇님  100  100   75   1  375
달님  100  100  100   1  400
별님  100  100   95   1  395
     국어   영어   수학   과학  학년   총점
홍련   65  100   70   70   1  305
콩쥐   70   95   65   90   1  320
팥쥐   85   65  100   85   1  335
햇님  100  100  100   75   1  375
달님  100  100  100  100   1  400
별님  100  100  100   95   1  395